services:
  yacht-agent:
    image: ghcr.io/yacht-sh/yacht-agent:latest
    container_name: yacht-agent
    restart: unless-stopped
    environment:
      - YACHT_SERVER_URL
      - YACHT_AGENT_ENROLLMENT_TOKEN
      - YACHT_AGENT_NAME
      - YACHT_AGENT_VERIFY_SSL
      - YACHT_AGENT_HEARTBEAT_INTERVAL
      - YACHT_AGENT_JOB_POLL_INTERVAL
      - YACHT_AGENT_VERSION
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
